# two parts: a request and a response. The two parts are separated by a '---'

Header header

uint32 frequency 
uint32 resolution # pixel per meter
float64 time # mimutes to mission
uint32 maxUS

# region to be reconnaissed
float64 startx
float64 starty
float64 endx
float64 endy
---
bool result
